spring:
  application:
    name: jwt-auth-service

# Swagger UI: http://localhost:8080/swagger-ui.html
# API Docs (JSON): http://localhost:8080/v3/api-docs
springdoc:
  swagger-ui:
    url: /v3/api-docs
    path: /swagger-ui.html
  api-docs:
    enabled: true
